%% convolutional encoder output
%    Generate ConvEncoder_DataOut_Matlab.txt & Compare the results
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% if we want to use standard document's example
clc, clear;
close all;

fileID = fopen('ConvEncoder_DataIn.txt', 'r');  % Standard example
DataIn = fscanf(fileID, '%d');

fclose('all');

%% If we want to use random data

% Open/create ConvEncoder_DataIn_Matlab.txt for writing
fileID = fopen('ConvEncoder_DataIn_Matlab.txt','w');

% Generate 100 random numbers (0 or 1)
DataIn = randi([0,1],96,1);
DataIn = [DataIn; zeros(6, 1)]; % Put 6 zeros at the end to bring the states back to zero

% Write input data to text file
fprintf(fileID, '%d\r\n', DataIn);                 

% Check whether the file is generated successfully
if fileID > 0                                      
     disp('File ConvEncoder_DataIn_Matlab.txt generated successfully !');
else
    disp('File ConvEncoder_DataIn_Matlab.txt NOT generated successfully !');
end

% Close all files
fclose('all');  

%% Compute convolutional encoder outputs

trellis = poly2trellis(7,[133 171]);
puncpat = [1;1;1;0]; % Rate : 2/3
% puncpat = [1;1;1;0;0;1]; % Rate : 3/4  
% calculate encoded data
Output = convenc(DataIn,trellis, puncpat);
%Output = convenc(DataIn,trellis); Rate : 1/2

%% write the output file

fileID = fopen('ConvEncoder_DataOut_Matlab.txt', 'w');
fprintf(fileID, '%d\r\n', Output);
fclose('all');
disp('File ConvEncoder_DataOut_Matlab.txt generated successfully !');
    
%% Compare HDL and Matlab

fileID = fopen('ConvEncoder_DataOut_Matlab.txt', 'r');  % Generated by Matlab
dataMatlab = fscanf(fileID, '%d');
fileID2 = fopen('ConvEncoder_DataOut_HDL.txt', 'r');    % Generated by HDL
dataHDL = fscanf(fileID2, '%d');
fclose('all');

if(isequal(dataMatlab, dataHDL))
   disp('Convolutional encoder output data for Matlab and HDL are equal!'); 
else 
   disp('Convolutional encoder output data for Matlab and HDL are NOT equal!');
end