%% convolutional encoder output
%    Generate ConvEncoder_DataOut_Matlab.txt & Compare the results
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% if we want to use standard document's example
clc, clear;
close all;

fileID = fopen('Scrambler_DataOut_Matlab.txt', 'r');  % Standard example
DataIn = fscanf(fileID, '%d');

fclose('all');

%% Compute convolutional encoder outputs

trellis = poly2trellis(7,[133 171]);
puncpat = [1;1;1;0]; % Rate : 2/3
% puncpat = [1;1;1;0;0;1]; % Rate : 3/4  
% calculate encoded data
%Output = convenc(DataIn,trellis, puncpat);
Output = convenc(DataIn,trellis); %Rate : 1/2

%% write the output file

fileID = fopen('ConvEncoder_DataOut_Matlab.txt', 'w');
fprintf(fileID, '%d\r\n', Output);
fclose('all');
disp('File ConvEncoder_DataOut_Matlab.txt generated successfully !');
    
%% Compare HDL and Matlab

fileID = fopen('ConvEncoder_DataOut_Matlab.txt', 'r');  % Generated by Matlab
dataMatlab = fscanf(fileID, '%d');
fileID2 = fopen('ConvEncoder_DataOut_HDL.txt', 'r');    % Generated by HDL
dataHDL = fscanf(fileID2, '%d');
fclose('all');

if(isequal(dataMatlab, dataHDL))
   disp('Convolutional encoder output data for Matlab and HDL are equal!'); 
else 
   disp('Convolutional encoder output data for Matlab and HDL are NOT equal!');
end