clc, clear;
close all;

numOfData = 96;
fileID = fopen('Serial2Parallel_DataIn.txt','w');
DataIn = randi([0,1],numOfData,1);
fprintf(fileID, '%d\r\n', DataIn);    
fclose('all');

%% 
Rate = 2/3;
if Rate == 1/2
    Output = DataIn;
end
if Rate == 3/4
    Output = [];
    for i = 1:numOfData
        if(mod(i, 4) == 3)
            Output = [Output; DataIn(i); 0];
        else
            if(mod(i, 4) == 0)
                Output = [Output; 0; DataIn(i)];
            else
                Output = [Output; DataIn(i)];
            end
        end
    end
end    
if Rate == 2/3
    Output = [];
    for i = 1:numOfData
        if(mod(i, 3) == 0)
            Output = [Output; DataIn(i); 0];
        else
            Output = [Output; DataIn(i)];
        end
    end
end
%%

fileID = fopen('Serial2Parallel_DataOut_Matlab.txt', 'w');
fprintf(fileID, '%d\r\n', Output);
fclose('all');
disp('File Serial2Parallel_DataOut_Matlab.txt generated successfully !');
%% Compare HDL and Matlab

fileID = fopen('Serial2Parallel_DataOut_Matlab.txt', 'r');  % Generated by Matlab
dataMatlab = fscanf(fileID, '%d');
fileID2 = fopen('Serial2Parallel_DataOut_HDL.txt', 'r');    % Generated by HDL
dataHDL = fscanf(fileID2, '%d');
fclose('all');

if(isequal(dataMatlab, dataHDL))
   disp('Serial2Parallel output data for Matlab and HDL are equal!'); 
else 
   disp('Serial2Parallel output data for Matlab and HDL are NOT equal!');
end