%% Deinterleaver output
%    Compare the results
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clc, clear;
close all;

fileID = fopen('Interleaver_DataOut_Matlab.txt', 'r');  % Generated by Matlab
DataIn = fscanf(fileID, '%d');
fclose('all');
Length = [0;1;1;0;0;0;0;0;0;0;0;0];
RATE = [1;1;0;1];
inputData = [zeros(30, 1); RATE; 0; Length; 0; zeros(6, 1); DataIn]; 
% Open/create Deinterleaver_DataIn.txt for writing
fileID = fopen('Deinterleaver_DataIn.txt','w');
fprintf(fileID, '%d\r\n', inputData);    
fclose('all');

%% Compare HDL and Matlab

fileID = fopen('ConvEncoder_DataOut_Matlab.txt', 'r');  % Generated by Matlab
dataMatlab = fscanf(fileID, '%d');

fileID2 = fopen('Deinterleaver_DataOut_HDL.txt', 'r');    % Generated by HDL
dataHDL = fscanf(fileID2, '%d');
fclose('all');

if(isequal(dataMatlab, dataHDL))
   disp('Deinterleaver output data for Matlab and HDL are equal!'); 
else 
   disp('Deinterleaver output data for Matlab and HDL are NOT equal!');
end