%% Matlab work 

%% Scrambler input & Descrambler output
%    Generate Scrambler_DataIn_Matlab.txt & Descrambler_DataOut_Matlab.txt
%    Scrambler input data & Descrambler output data as a txt file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clc, clear;
close all;

% Open/create Scrambler_DataIn_Matlab.txt for writing
fileID = fopen('Scrambler_DataIn_Matlab.txt','w');

% Generate 100 random numbers (0 or 1)
DataIn = randi([0,1],100,1);                       

% Write input data to text file
fprintf(fileID, '%d\r\n', DataIn);                 

% Check whether the file is generated successfully
if fileID > 0                                      
     disp('File Scrambler_DataIn_Matlab.txt generated successfully !');
else
    disp('File Scrambler_DataIn_Matlab.txt NOT generated successfully !');
end

% Close all files
fclose('all');                                    

% Open Descrambler_DataOut_Matlab.txt for writing
fileID = fopen('Descrambler_DataOut_Matlab.txt','w'); 

% Descrambler output data is equal to scrambler input data 
fprintf(fileID, '%d\r\n', DataIn);       

% Check whether the file is generated successfully
if fileID > 0                                         
    disp('File Descrambler_DataOut_Matlab.txt generated successfully !');
else
    disp('File Descrambler_DataOut_Matlab.txt NOT generated successfully !');
end

% Close all files
fclose('all');                                    

%% Scrambler output & Descrambler input & Sequence
%     Generate Scrambler_DataOut_Matlab.txt & Scrambler_Sequence_Matlab.txt 
%     &     Descrambler_DataIn_Matlab.txt & Descrambler_Sequence_Matlab.txt
%           (Scrambler Matlab output data & sequence data as a txt file)
%           (Descrambler Matlab input data & sequence data as a txt file)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% InitSequence: 7'b101_1101 
scramInit = 93;

% Convert decimal numbers to binary vectors
scramblerInitBits = de2bi(scramInit, 7, 'left-msb')'; 

buffSize = size(DataIn,1);

% I: Generated sequence 
I = zeros(buffSize, 1);                                 

for d = 1:buffSize
    I(d) = xor(scramblerInitBits(1), scramblerInitBits(4)); % x7 xor x4
    scramblerInitBits(1:end-1) = scramblerInitBits(2:end);  % Left-shift
    scramblerInitBits(7) = I(d);                            % Update x1
end

% Generating output data
y = xor(I, DataIn);                                      

% Check my generated output data with matlab function's output data
% wlanScramble is Matlab's function generates the same output
scrambledData = wlanScramble(DataIn, scramInit);        

if(isequal(scrambledData, y))
    disp('My generated scrambler output data & Matlab function output are equal !');
    
    fileID = fopen('Scrambler_DataOut_Matlab.txt', 'w');
    fprintf(fileID, '%d\r\n', y);
    fclose('all');
    disp('File Scrambler_DataOut_Matlab.txt generated successfully !');
    
    fileID = fopen('Descrambler_DataIn_Matlab.txt', 'w');
    fprintf(fileID, '%d\r\n', y);
    fclose('all');
    disp('File Descrambler_DataIn_Matlab.txt generated successfully !');
    
    fileID = fopen('Scrambler_Sequence_Matlab.txt', 'w');
    fprintf(fileID, '%d\r\n', I);
    fclose('all');
    disp('File Scrambler_Sequence_Matlab.txt generated successfully !');
    
    fileID = fopen('Descrambler_Sequence_Matlab.txt', 'w');
    fprintf(fileID, '%d\r\n', I);
    fclose('all');
    disp('File Descrambler_Sequence_Matlab.txt generated successfully !');
end

%% Scrambler: Check output files
%             Check whether the output file that testbench generated
%             is equal to Matlab's output file or not
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fileID = fopen('Scrambler_DataOut_Matlab.txt', 'r');  % Generated by Matlab
dataMatlab = fscanf(fileID, '%d');
fileID2 = fopen('Scrambler_DataOut_HDL.txt', 'r');    % Generated by HDL
dataHDL = fscanf(fileID2, '%d');
fclose('all');

if(isequal(dataMatlab, dataHDL))
   disp('Scrambler output data for Matlab and HDL are eqaul !'); 
else 
   disp('Scrambler output data for Matlab and HDL are NOT eqaul !');
end

%% Descrambler: Check output files
%             Check whether the output file that testbench generated
%             is equal to Matlab's output file or not
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fileID = fopen('Descrambler_DataOut_Matlab.txt', 'r');  % Generated by Matlab
dataMatlab = fscanf(fileID, '%d');
fileID2 = fopen('Descrambler_DataOut_HDL.txt', 'r');    % Generated by HDL
dataHDL = fscanf(fileID2, '%d');
fclose('all');

if(isequal(dataMatlab, dataHDL))
   disp('Descrambler output data for Matlab and HDL are eqaul !'); 
else 
   disp('Descrambler output data for Matlab and HDL are NOT eqaul !');
end

%% Scrambler: Check scrambling sequence files
%           Check whether the scrambling sequence file that testbench
%           generated is equal to Matlab's scrambling sequence file or not
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fileID = fopen('Scrambler_Sequence_Matlab.txt', 'r');   % Generated by Matlab
sequenceMatlab = fscanf(fileID, '%d');
fileID2 = fopen('Scrambler_Sequence_HDL.txt', 'r');     % Generated by HDL
sequenceHDL = fscanf(fileID2, '%d');

if(isequal(sequenceMatlab, sequenceHDL))
   disp('Scrambler Sequences for Matlab and HDL are equal !'); 
else
   disp('Scrambler Sequences for Matlab and HDL are NOT equal !');
end
fclose('all');

%% Decrambler: Check Decrambling sequence files
%           Check whether the Descrambling sequence file that testbench
%           generated is equal to Matlab's Descrambling sequence file or not
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fileID = fopen('Descrambler_Sequence_Matlab.txt', 'r');  % Generated by Matlab
sequenceMatlab = fscanf(fileID, '%d');
fileID2 = fopen('Descrambler_Sequence_HDL.txt', 'r');    % Generated by HDL
sequenceHDL = fscanf(fileID2, '%d');

if(isequal(sequenceMatlab, sequenceHDL))
   disp('Descrambler Sequences for Matlab and HDL are equal !'); 
else
   disp('Descrambler Sequences for Matlab and HDL are NOT equal !');
end
fclose('all');